// Static data for CV - fast loading and no API calls needed
export const educationData = [
  {
    id: 0,
    tabName: 'NEWCASTLE-MSC',
    university: 'NEWCASTLE UNIVERSITY',
    degree: 'MSC - COMPUTING SCIENCE',
    year: '2019-2020',
    location: 'Newcastle, UK',
    modules: [
      'Advanced Programming',
      'Data Management',
      'Distributed Systems',
      'Machine Learning',
      'Mobile and Ubiquitous Computing',
      'Security and Risk Management',
      'Software Engineering',
      'Web Technologies',
    ],
    GPA: 'Merit',
    summary:
      'I studied for one year at Newcastle University where I received a Masters of Science in Computing Science. I learned a lot about programming, data management, distributed systems, machine learning, mobile and ubiquitous computing, security and risk management, software engineering, and web technologies. I also learned about the importance of agile methodologies and the importance of teamwork in software development.',
    degreeImage:
      'https://degrees-rhys-cairns.s3.us-east-1.amazonaws.com/Newcastledegree.jpeg',
    universityWebsite: 'https://ncl.ac.uk/',
    current: true,
  },
  {
    id: 1,
    tabName: 'AVILA-MBA',
    university: 'AVILA UNIVERSITY',
    degree: 'MBA',
    year: '2017-2019',
    location: 'Kansas City, MO',
    modules: [
      'Accounting',
      'Economics',
      'Finance and Banking',
      'International Finance',
      'Financial Management',
      'Advanced Marketing',
      'Strategic Management',
      'Strategy',
    ],
    GPA: '3.72',
    summary:
      'I studied for two years at Avila University where I received a Masters of Business Administration. I learned a lot about accounting, economics, finance, management, marketing, operations, and strategy. I also learned about the importance of leadership and the importance of teamwork in business.',
    degreeImage:
      'https://degrees-rhys-cairns.s3.us-east-1.amazonaws.com/aviladegree.jpeg',
    universityWebsite: 'https://www.avila.edu/',
    current: false,
  },
  {
    id: 2,
    tabName: 'UMKC-BA',
    university: 'UNIVERSITY OF MISSOURI - KANSAS CITY',
    degree: 'BA - FINANCE',
    year: '2014-2016',
    location: 'Kansas City, MO',
    modules: [
      'Financial Management',
      'Investment Management',
      'Financial Markets',
      'Financial Institutions',
      'International Finance',
      'Risk Management',
      'Financial Modeling',
      'Corporate Finance',
      'Financial Statement Analysis',
    ],
    GPA: '3.28',
    summary:
      "I studied for two years at UMKC where I received a Bachelor of Business Administration in Finance. I learned a lot about the financial markets, financial institutions, and investment management. I also learned about financial modeling, corporate finance, and financial statement analysis. During my time I was also a member of the men's soccer team. I had transferred from Longwood University where I spent my first two years of my undergrad.",
    degreeImage:
      'https://degrees-rhys-cairns.s3.us-east-1.amazonaws.com/UMKCdegree.jpeg',
    universityWebsite: 'https://ncl.ac.uk/',
    current: false,
  },
  {
    id: 3,
    tabName: 'AWS-DA',
    university: 'AMAZON WEB SERVICES',
    degree: 'CERTIFIED DEVELOPER ASSOCIATE',
    year: '2024',
    location: 'Remote',
    modules: [
      'AWS Fundamentals',
      'AWS Cloud Development Kit',
      'AWS Lambda',
      'AWS API Gateway',
      'AWS DynamoDB',
      'AWS Cognito',
      'AWS S3',
      'AWS CloudFront',
      'AWS CloudFormation',
    ],
    GPA: 'Pass',
    summary:
      'I spent around 3 months studying for the AWS Developer Associate certification. I learned a lot about the AWS cloud and how to develop applications using AWS services. I learned about AWS Lambda, AWS API Gateway, AWS DynamoDB, AWS Cognito, AWS S3, AWS CloudFront, and AWS CloudFormation. I also learned about the importance of security and the importance of scalability in cloud development.',
    degreeImage:
      'https://degrees-rhys-cairns.s3.us-east-1.amazonaws.com/AWS.jpeg',
    universityWebsite:
      'https://www.credly.com/badges/753b00d6-5b65-481f-adfc-f0f5b605a8f9/linked_in_profile',
    current: false,
  },
];

export const experienceData = [
  {
    id: 0,
    title: 'SOFTWARE ENGINEER',
    company: 'KINGFISHER',
    tabName: 'KINGFISHER',
    companyDescription:
      'An international home improvement company with over 2,000 stores, supported by a team of over 78,000 colleagues.',
    technologies: [
      'Vuejs',
      'Vuex',
      'React',
      'Node',
      'Express',
      'Mocha',
      'Cypress',
      'MongoDB',
      'Git',
      'Gitlab',
      'Jira',
      'Agile',
      'Event driven',
      'Postgres',
    ],
    date: '2022 - PRESENT',
    description: [
      'Key member of the Digital Colleague Application team supporting 50,000+ employees across Europe.',
      'Developed solutions saving £3 million annually and reducing task time by 70%.',
      'Built and maintained ~15 microservices using Vue.js, Node.js, MongoDB, and event-driven architecture.',
      'Ensured code quality with CI/CD, peer reviews, and automated testing (Mocha, Cypress).',
      'Led release management and provided the highest on-call support (14 days/month).',
      'Progressed from contractor to permanent role at Kingfisher PLC in March 2024.',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/kingfisher.png',
    website: 'www.kingfisher.com',
    current: true,
  },
  {
    id: 1,
    title: 'SOFTWARE ENGINEER',
    company: 'LA FOSSE',
    tabName: 'LAFOSSE',
    companyDescription: 'Specialist Tech IT Talent Solutions Agency',
    date: '2021-2024',
    description: [
      'Completed a 9 week intensive training course in software engineering',
      'Developed multiple applications using React, Node, Express, MongoDB and Python',
      'Hired at Kingfisher as a Software Engineer after completing the training course',
      'Created and presented a newly developed application once every three weeks to the group',
      'Passed numerous technical exams and assessments to complete the course',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/lafosselogo.jpeg',
    website: 'https://www.lafosse.com/',
    technologies: [
      'React',
      'Redux',
      'Node',
      'Express',
      'Jest',
      'Python',
      'Django',
      'Git',
      'Github',
    ],
    current: false,
  },
  {
    id: 2,
    title: 'BUSINESS AND SUPPORT ANALYST',
    company: 'RIGHTMOVE',
    tabName: 'RIGHTMOVE',
    companyDescription: "The UK's largest property portal",
    date: '2020-2021',
    description: [
      'Provide technical support: Help users with technical inquiries and provide advice on possible solutions',
      'Diagnose and solve issues: Use diagnostic tools to identify and fix software or hardware faults',
      'Maintain systems: Install updates and security patches, and check for vulnerabilities',
      'Document interactions: Record interactions with users to improve future support strategies',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/rightmovelogo.jpeg',
    website: 'www.rightmove.co.uk',
    technologies: ['SQL'],
    current: false,
  },
  {
    id: 3,
    title: 'HEAD COACH',
    company: 'LITTLE KICKERS',
    tabName: 'LITTLEKICKERS',
    companyDescription: "The UK's largest pre-school football academy",
    date: '2021-2022',
    description: [
      'Coaching: Lead classes for children ages 18 months to 8 years old. This includes planning sessions, role-playing, and communicating with children, parents, and carers.',
      'Team management: Recruit and train new coaches, manage the coach schedule, and conduct coach assessments.',
      'Events: Plan and lead birthday parties, school clubs, and nursery visits.',
      'Ceremonies: Lead badge and certificate ceremonies.',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/littlekickerslogo.png',
    website: 'www.littlekickers.co.uk',
    current: false,
  },
  {
    id: 4,
    title: 'CUSTOMER SERVICE ASSISTANT',
    company: 'SAINSBURYS',
    tabName: 'SAINSBURYS',
    companyDescription: "The UK's second largest supermarket chain",
    date: '2019-2020',
    description: [
      'Customer service: Help customers find products, answer questions, and explain product information',
      'Checkouts: Process payments, pack orders, and keep things tidy',
      'Self-service tills: Work at self-service tills',
      'Kiosks: Work at kiosks',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/sainsburyslogo.png',
    website: 'www.sainsburys.co.uk',
    current: false,
  },
  {
    id: 5,
    title: 'ASSISTANT ATHLETIC DIRECTOR/CAMP SPECIALIST',
    company: 'CAMP WALT WHITMAN',
    tabName: 'CAMPWALTWHITMAN',
    companyDescription: "New Hampshire's Best Sleepaway Summer Camp",
    date: 'Summer - 2016,2017,2018,2019',
    description: [
      "Manage and oversee the camp's athletic programs, scheduling sports activities and tournaments.",
      'Supervise and mentor coaches, counselors, and junior staff to ensure a high-quality experience for campers.',
      'Implement safety protocols and risk management procedures for all athletic activities.',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/cwwlogo.png',
    website: 'www.campwalt.com',
    current: false,
  },
  {
    id: 6,
    title: 'CAPTAIN/LEAD MOVER',
    company: 'BELLHOPS',
    tabName: 'BELLHOPS',
    companyDescription: 'A moving company distributed across the United States',
    date: '2017-2019',
    description: [
      'Lead and coordinate moving crews to ensure efficient and damage-free relocations.',
      'Provide excellent customer service by communicating with clients and addressing concerns.',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/bellhopslogo.jpeg',
    website: 'www.getbellhops.com',
    current: false,
  },
  {
    id: 7,
    title: 'GRADUATE COACHING ASSISTANT/RESIDENT ASSISTANT',
    company: 'AVILA UNIVERSITY',
    tabName: 'AVILA',
    companyDescription: 'A private university in Kansas City, Missouri',
    date: '2017-2019',
    description: [
      'Assist head coaches in planning and running team practices and training sessions.',
      'Analyze game footage and provide strategic insights to improve team performance.',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/avilalogo.png',
    website: 'www.avila.edu',
    current: false,
  },
  {
    id: 8,
    title: 'SOCCER COACH',
    company: 'LEGENDS KC',
    tabName: 'LEGENDSKC',
    companyDescription: 'A youth soccer club in Kansas City, Missouri',
    date: '2017-2019',
    description: [
      'Develop and implement training programs tailored to players of various skill levels across 11 teams.',
      'Manage game strategies, player development, and in-game adjustments to maximize team performance.',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/legendskclogo.png',
    website: 'www.legendssoccer.com',
    current: false,
  },
  {
    id: 9,
    title: 'ACCOUNTING SPECIALIST',
    company: 'AMC',
    tabName: 'AMC',
    companyDescription: 'The largest movie theater chain in the world',
    date: '2017',
    description: [
      'Manage financial transactions, reconciliations, and reporting to ensure accuracy in accounting records.',
    ],
    logo: 'https://experience-rhys-cairns.s3.us-east-1.amazonaws.com/amclogo.png',
    website: 'www.amctheatres.com',
    current: false,
  },
];

export const aboutMeData = [
  {
    id: 1,
    title: 'IM THE BALD ONE',
    description:
      'So this is me ...and the better half (at least she thinks so). We have been together for the past seven years. I am originally from Newcastle and she is from Dublin. We met in the mountains of New Hampshire working at Camp Walt Whitman and have not looked back since. We have been on some amazing adventures together and I am looking forward to many more.',
    imageUrl:
      'https://aboutme-rhys-cairns.s3.us-east-1.amazonaws.com/meandmrs.jpg',
  },
  {
    id: 2,
    title: 'WHY A SOFTWARE ENGINEER',
    description:
      "The best way I can explain this is that I don't see being a software engineer as just a job—I see it as problem-solving for another job. Every piece of code we write is built upon an underlying role or industry that we need to understand first. For example, if you are a software engineer at an airline company, you can't just write code—you need to understand aviation systems and processes. The same applies if you are developing software for a hospital; you need to grasp medical workflows and patient care. Even in sports technology, understanding performance analytics or athlete tracking is key. That's what I love about being a software engineer: the opportunity to continuously learn about different fields and industries.",
    imageUrl:
      'https://aboutme-rhys-cairns.s3.us-east-1.amazonaws.com/oceancity.jpg',
  },
  {
    id: 3,
    title: 'FUN TIMES',
    description:
      'In my spare time I love to play football, go hiking and have a laugh with the lads. I have been playing football since I was 4 years old and it has taken me across the Atlantic Ocean where I played collegiate soccer for 4 years and coached for 2 years. Nowadays I just play for fun and to keep fit but I still love playing. For my sins I am a Manchester United supporter, which, with each passing year, seems to become harder and harder. The picture to the left is a hiking trip I took with the lads I play football with to the Lake District. It was a great day even if we nearly had a coronary climbing the mountain.',
    imageUrl: 'https://aboutme-rhys-cairns.s3.us-east-1.amazonaws.com/lads.jpg',
  },
];

export const projectsData = [
  {
    title: 'COLLEGE ATHLETE BASE',
    description:
      'A new scholarship platform for future or current collegiate athletes. It offers a place where everyone can show off their talents and be recognized by coaches across the nation',
  },
  {
    title: 'COPYCAT',
    description:
      'There are hedge funds currently that follow the trades of the top investors in the world. This app will allow you to follow the trades of the top investors in the world without entering a hedge fund.',
  },
  {
    title: 'DIY MOVE',
    description:
      'Why pay 3% for someone to sell your house when you can do it yourself? DIYMove is a platform that allows you to sell your house without a real estate agent.',
  },
];
